package lk.ijse.navigation;

public enum Routes {

    CUSTOMER,EMPLOYEE, LOGIN, ADMIN, HOME, ADD_EMPLOYEE, STORE, ADD_ITEM, RAW_MATERIAL, PAYMENT, SUPPLIER, ADD_SUPPLIER,
    ADD_CUSTOMER, ADD_MATERIAL, ADD_PAYMENT, ORDER, ORDER_DETAIL
}
